# Generated by Django 3.2.11 on 2022-01-18 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип данных',
                'verbose_name_plural': 'Типы данных',
            },
        ),
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Коэффициент корреляции')),
                ('p_value', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Проверка наличия корреляции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('x_data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x_data_type', to='welltory.datatype', verbose_name='Тип данных X')),
                ('y_data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='y_data_type', to='welltory.datatype', verbose_name='Тип данных Y')),
            ],
            options={
                'verbose_name': 'Корреляция',
                'verbose_name_plural': 'Корреляции',
            },
        ),
    ]
