# Generated by Django 3.2.11 on 2022-01-18 12:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('welltory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='correlation',
            unique_together={('user', 'x_data_type', 'y_data_type')},
        ),
    ]
